name: amy

ghc-options: -Wall

library:
  source-dirs: library
  dependencies:
    - base
    - bytestring
    - containers
    - groom
    - llvm-hs
    - llvm-hs-pure
    - megaparsec
    - mtl
    - parser-combinators
    - prettyprinter
    - scientific
    - text
    - transformers

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - amy
      - base
      - containers
      - hspec
      - hspec-megaparsec
      - megaparsec
      - text

executables:
  amy:
    source-dirs: executables
    main: Main.hs
    dependencies:
      - amy
      - base
      - bytestring
      - filepath
      - haskeline
      - llvm-hs-pretty
      - megaparsec
      - mtl
      - optparse-applicative
      - process
      - text
